site_name: vecs
site_url: https://olirice.github.io/vecs
site_description: Vector Database Client for pgvector

repo_name: olirice/vecs
repo_url: https://github.com/olirice/vecs

theme:
    name: 'material'
    features:
      - navigation.expand
    palette:
        primary: grey
        accent: red
nav:
  - Quickstart:
    - API: api.md
    - Hosting: hosting.md
  - Concepts:
    - Collections: concepts_collections.md
    - Indexes: concepts_indexes.md
    - Metadata: concepts_metadata.md
  - Integrations:
    - OpenAI: integrations_openai.md
  - Support:
    - Changelog: support_changelog.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences